### PR TITLE
docs: add Install, Use, Learn, & Contribute

### PR DESCRIPTION
**Pull request by chadoh**
Copied How it Works from current https://raen.dev/admin

Copied Install and Use from https://raen.dev/docs, with some additions
from https://near-sdk.io/

Added a "Contribute" section stub

### CODE REVIEW

**Review by willemneal — APPROVED** [review]
Could also add a link to https://raen.dev/docs/guide/installation.html

**Comment by chadoh** [comment]
@willemneal thinking about it more, it feels unusual for a CLI project's GitHub README to link away for installation instructions. I decided to copy both installation instructions and usage instructions from current https://raen.dev/docs to this README, with some extra detail copied from https://near-sdk.io. It's very common for project READMEs to include all of these as well as a Contribute section, so I also added a "Contribute" stub at the end. If you like it all living here, we could stop linking to `/docs` and link here instead, and eventually remove the `docs` repo.

**Comment by willemneal** [comment]
Yeah I figured that the docs section could also cover things like common errors and more technical details.  But I'm definitely down to keep the install directions front and center.

**Comment by chadoh** [comment]
Yeah, `/docs` could be a great place for more advanced information, but I think for install and basic usage we could link to this repo. I'll change current links to `/docs` to this project instead, for now, and we can start linking to `/docs` when it becomes a more useful deep-dive into various topics.

**Comment by chadoh** [comment]
Do you approve the current README, @willemneal?

**Review by willemneal — APPROVED** [review]
Great!

**Pull request merged**
